### ISSUE TITLE
Error with "docker pull emdupre/hd4630_workshops"

### ISSUE THREAD

**Issue by changy12** [emdupre/hd4630_workshops#1]
Dear Elizabeth:
I'm student Ziyi Chen in HD 4630.

The following error comes when I entered "docker pull emdupre/hd4630_workshops":

dhcp-ccc-6613:Downloads chenziyi$ docker pull emdupre/hd4630_workshops
Using default tag: latest
Warning: failed to get default registry endpoint from daemon (Cannot connect to the Docker daemon at tcp://192.168.99.100:2376. Is the docker daemon running?). Using system default: https://index.docker.io/v1/
Cannot connect to the Docker daemon at tcp://192.168.99.100:2376. Is the docker daemon running?

Then I restart Dockertoolbox and type again, and within 1 second it stopped and said:
Using default tag: latest
latest: Pulling from emdupre/hd4630_workshops
Digest: sha256:5c37689dd203e0ed439a977451cdaf7b1e96ebbfc4e6f95b65882a55a20f2ec3
Status: Image is up to date for emdupre/hd4630_workshops:latest

I do not understand what happened. Could you help me?
Thank you
         Ziyi

**Comment by emdupre** [comment]
It sounds like you hadn't started a Docker session before running the command. You need Docker running before you're able to use it. For Docker toolbox, this usually involves opening the application Docker Quickstart Terminal. This will launch a new Terminal on a Mac OSX, where you can issue the command 
`docker pull emdupre/hd4630_workshops`

It sounds like the file downloaded incorrectly before since the application wasn't launched, so try these commands in a new Docker Quickstart Terminal:
`docker rmi -f $(docker images -a )`
`docker rm $(docker ps -aq)`

Once those are run, re-run 
`docker pull emdupre/hd4630_workshops`
Be sure to use the Docker Quickstart Terminal throughout!
